### ISSUE TITLE
Large and Corrupt Image Files should provide the admin with validation to avoid dead images and dupes.

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#102]
This is memory #183.

- I used a .jpg
- When I submitted the memory I received an error message that the submission failed
- but when I went to memories, it was there. 
- It shows image address http://res.cloudinary.com/hodsx14x9/image/upload/t4ocpojam5vpt8sdoziq.jpg
- But This res.cloudinary.com page can’t be found

<img width="436" alt="image" src="https://user-images.githubusercontent.com/10439748/159498218-88151ffd-6ec3-44bd-9125-dec1f2c8f650.png">

**Comment by brotherclone** [comment]
Ok - so that image was 75MB and over 8000 px @ print dpi. I will add a reject for uploads that exceed 10mb (max size on cloudinary). The other issue is related, if you hit submit again when a large or corrupt image doesn't go through it will create a dupe - for this I'll validate unique titles.

**Comment by rcampany** [comment]
Got it!

From: Gabriel Walsh ***@***.***>
Date: Tuesday, March 22, 2022 at 11:48 AM
To: brotherclone/peter-koper ***@***.***>
Cc: campany ***@***.***>, Author ***@***.***>
Subject: Re: [brotherclone/peter-koper] Image issues (Issue #102)

Ok - so that image was 75MB and over 8000 px @ print dpi. I will add a reject for uploads that exceed 10mb (max size on cloudinary). The other issue is related, if you hit submit again when a large or corrupt image doesn't go through it will create a dupe - for this I'll validate unique titles.
