### ISSUE TITLE
no headline???

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#113]
Peter has asked if we can _not_ require headlines for memories.

There is the practical issue of editing or deleting live memories. How do we identify a memory from the front end in the admin area without a headline?

**Comment by brotherclone** [comment]
I could add either "show headline" or an admin description field to memories. Which would be better for you?

**Comment by rcampany** [comment]
Hmm.
let me see if I understand. 

- Headline is still required
- We add a tick box to choose to display or not
- I can use it for a headline - or admin description that would help me find the memory in admin, e.g., Peter in red shirt

**Comment by brotherclone** [comment]
Correct. 100%. Let me know if that works for you.

**Comment by rcampany** [comment]
Sounds perfect

From: Gabriel Walsh ***@***.***>
Date: Sunday, March 27, 2022 at 5:28 PM
To: brotherclone/peter-koper ***@***.***>
Cc: campany ***@***.***>, Author ***@***.***>
Subject: Re: [brotherclone/peter-koper] no headline??? (Issue #113)

Correct. 100%. Let me know if that works for you.

**Comment by rcampany** [comment]
Peter is very excited by this update
