### ISSUE TITLE
PDF loading in wrong page area

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#120]
This is a new bug. Clicking a PDF _seems_ to not open it. But if you scroll to the top of the page, the PDF is open up there. PDFs used to open in place.

Also- the navigation to pages beyond the first does not seem to w ork.
Screen recording here:
https://drive.google.com/file/d/1vm_la2BL95y4cXeRuGFCshi4gQNjx6Xi/view?usp=sharing

**Comment by brotherclone** [comment]
yeah - saw this too! #119  Annoying! Sorry will fix ASAP.
