### ISSUE TITLE
New Feature - site credits

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#126]
Peter wants us to get credit for the site, T'would be nice, given the folks who may be looking at the site. (Small tidbit that is not directly related to this ticket, his friend Kitsy is cousins with both Chris Van Hollen and Ken Burns. There are some degrees of separation most people would never guess.)

Anyway - I **_hate_** the typical footer credits. Got any ideas?

**Comment by brotherclone** [comment]
How about a memory? Or a story? We could also sneak in a subtle link on the Drop a Story page to a credits page?
