### ISSUE TITLE
Categories in Didot - But maybe a different Dido?

### ISSUE THREAD

**Issue by brotherclone** [brotherclone/peter-koper#128]

**Comment by brotherclone** [comment]
<img width="923" alt="Screen Shot 2022-03-31 at 7 53 40 AM" src="https://user-images.githubusercontent.com/2085319/161049046-99d07650-f65e-4d98-a06f-45831f3308d5.png">
They are in Didot (a fancier kind on Adobe by Monotype  Foundry https://fonts.adobe.com/foundries/monotype) but do you want me to switch Didot to the Google Font Didot for the whole site? Perhaps I have the wrong Didot?

**Comment by rcampany** [comment]
To clarify - Peter was reacting to when the subcategory is a heading. 
Seems like you would need to add some special casing to make it display differently than when a category is a heading.

For now let's label this P3-ish
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/10439748/161070589-fc9b6d3a-3ed6-4250-9837-4050b49da28a.png">

**Comment by brotherclone** [comment]
Ohhhhhh! No problem - I'll  add a variable to the SubCat and Cat controllers that will toggle that. Sorry I didn't get it at first.
