### ISSUE TITLE
Click to read visibilty an dtreatment

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#133]
Click to read is often hard to see.

Maybe consider a white field with Flaneur Red icon and text?

<img width="259" alt="image" src="https://user-images.githubusercontent.com/10439748/161120214-6a6e2f67-597d-47ec-9916-0edb02bf6af9.png">

<img width="257" alt="image" src="https://user-images.githubusercontent.com/10439748/161120143-e10bc5be-1c15-4507-8cef-47a99dc7bb73.png">

 
<img width="202" alt="image" src="https://user-images.githubusercontent.com/10439748/161120261-478d5b16-0475-4fe3-8136-9b9a8bde48dc.png">

**Comment by brotherclone** [comment]
<img width="461" alt="Screen Shot 2022-03-31 at 3 49 42 PM" src="https://user-images.githubusercontent.com/2085319/161137866-d45d5674-3e2c-4324-8f07-92011313c6b7.png">
<img width="261" alt="Screen Shot 2022-03-31 at 3 50 32 PM" src="https://user-images.githubusercontent.com/2085319/161137867-e4dbc3fe-d97a-4378-bc25-f4cde8a6345a.png">
<img width="410" alt="Screen Shot 2022-03-31 at 3 53 10 PM" src="https://user-images.githubusercontent.com/2085319/161137869-6c57915c-abfa-4e08-8e53-ab9488b9bbf4.png">
let me know which one you like - or I can try something else.

**Comment by rcampany** [comment]
what if "click to read" was a lighter field?
<img width="197" alt="image" src="https://user-images.githubusercontent.com/10439748/161141233-b2a48790-629a-4fa0-8297-c96ef9a80099.png">

**Comment by brotherclone** [comment]
Icon - RED fill, no background
"Click to Read" White, background? Or do you mean that the background should be lighter? Sorry if I'm being dense.

**Comment by brotherclone** [comment]
<img width="327" alt="Screen Shot 2022-03-31 at 5 05 45 PM" src="https://user-images.githubusercontent.com/2085319/161149384-50243fc3-571d-4beb-b2cd-9dca5fe33db6.png">

**Comment by rcampany** [comment]
Looks great!
