### ISSUE TITLE
troubleshoot video

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#136]
The video for memory #279 - Bring the momoey home only opens as audio.

It is video #2 
http://res.cloudinary.com/hodsx14x9/video/upload/v1648761317/und5t8ylm18uympkaxr7.mp4
--

Probably user error ...

**Comment by brotherclone** [comment]
can you send me the source file?

**Comment by rcampany** [comment]
https://drive.google.com/file/d/1hmodJUIluo14BqjpZERVSH_AnyR2pQv8/view?usp=sharing

From: Gabriel Walsh ***@***.***>
Date: Friday, April 1, 2022 at 8:30 AM
To: brotherclone/peter-koper ***@***.***>
Cc: campany ***@***.***>, Author ***@***.***>
Subject: Re: [brotherclone/peter-koper] troubleshoot video (Issue #136)

can you send me the source file?

**Comment by brotherclone** [comment]
It looks like videos can't have AAC codecs (apple uses for DRM). They need to be H.264 (I can batch compress and upload for you if you wanna just name them the same as the corresponding memory. BUT this did show I sized the video for our one vertical phone view and there's a gap on top - so I'll keep this open to fix that.

**Comment by rcampany** [comment]
Could I use Topaz video enhance to fix the videos?

From: Gabriel Walsh ***@***.***>
Date: Friday, April 1, 2022 at 10:59 AM
To: brotherclone/peter-koper ***@***.***>
Cc: campany ***@***.***>, Author ***@***.***>
Subject: Re: [brotherclone/peter-koper] troubleshoot video (Issue #136)

It looks like videos can't have AAC codecs (apple uses for DRM). They need to be H.264 (I can batch compress and upload for you if you wanna just name them the same as the corresponding memory. BUT this did show I sized the video for our one vertical phone view and there's a gap on top - so I'll keep this open to fix that.
