### ISSUE TITLE
video frames are cropped

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#148]
video frames are cropped - both landscape and portrait

**full frame Memory 430**
<img width="754" alt="image" src="https://user-images.githubusercontent.com/10439748/161978612-87e3d392-fca1-46d1-902f-be847260f7aa.png">

**what the player shows Memory 430**
<img width="760" alt="image" src="https://user-images.githubusercontent.com/10439748/161978721-99550814-b3a1-4223-a1e5-9403c3af0e33.png">

**full frame Memory 452**

<img width="293" alt="image" src="https://user-images.githubusercontent.com/10439748/161978843-45c7454e-dc8e-45b7-9adf-d3082dbf8273.png">

**what the player shows Memory 452**
<img width="659" alt="image" src="https://user-images.githubusercontent.com/10439748/161978919-79107c92-ec9e-42ec-9517-c551284d42f6.png">

**Comment by brotherclone** [comment]
Hmm... I didn't realize that the aspect ratio could change. We might need to change the data model to manually set it. For example house tour would be 16:9 and demolition would be 9:16 old AMW would be 4:3. Any other media types?

**Comment by rcampany** [comment]
Haven’t found any others yet


From: Gabriel Walsh ***@***.***>
Date: Wednesday, April 6, 2022 at 1:29 PM
To: brotherclone/peter-koper ***@***.***>
Cc: campany ***@***.***>, Author ***@***.***>
Subject: Re: [brotherclone/peter-koper] video frames are cropped (Issue #148)

Hmm... I didn't realize that the aspect ratio could change. We might need to change the data model to manually set it. For example house tour would be 16:9 and demolition would be 9:16 old AMW would be 4:3. Any other media types?

**Comment by rcampany** [comment]
Jome movies are 16:9 as converted to MP4. Here is an example 
https://vimeo.com/manage/videos/696762432
