### ISSUE TITLE
where do guest memories live? How are they browsed?

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#162]
Currently, the only way to see submitted/approved memories is to navigate to "drop your stories."
Can we:
a.) incorporate guest stories into the feeds somehow? This would require the guest to specify the category, I think.
b.) When a guest memory is submitted via an existing memory, can it display so that the relationship to the memory is clear? e.g. - adjacent? 

<img width="1221" alt="getting to guest memories" src="https://user-images.githubusercontent.com/10439748/167503765-fe1ed44f-5138-4c46-8bb9-05e08d822264.png">

**Comment by brotherclone** [comment]
Currently, the only way to see submitted/approved memories is to navigate to "drop your stories."
-> They also appear in the associated memory if you've added there.

**Comment by rcampany** [comment]
-> They also appear in the associated memory if you've added there.

When looking at a memory that has a guest comment, there's no indication that one exists.
You have to click on "add your story," then scroll down to see that there is a memory

https://user-images.githubusercontent.com/10439748/167659059-ce05e5bf-8d11-4a99-abfd-5df62e689541.mp4

**Comment by rcampany** [comment]
Peter is not ready to have people submit comments yet. But I can submit and approve more test comments. Any special requests for his? Like add lots of comments to a specific memory?

**Comment by brotherclone** [comment]
I just need something enough that when I publish you can check it out. Even one story (like the aunt) with three images attached to a memory and I should be okay.
