### ISSUE TITLE
Required fields on memory submissions

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#163]
1.) Title, body, email address, and name should be required fields (currently only title and body are required.)
2.) we need to indicate which form fields are required.  Currently, only "title" is indicated as required. 
3.) When I submit the form without a required field (I tested with _body_ missing) there is no clear error message.
-It takes me to https://www.peterkoper.com/dropped_stories  - and it would seem to the user that their submission was successful. 
-If the user enters "Koper" they are then taken to a page that shows the error message. 

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/10439748/167507585-6bbb692f-d964-4dca-9d26-72b758e9cd42.png">

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/10439748/167507786-eeefb7b2-108a-492c-82d5-11e625740dbe.png">

**Comment by brotherclone** [comment]
-If the user enters "Koper" they are then taken to a page that shows the error message. <-I can't reproduce.
https://user-images.githubusercontent.com/2085319/167510251-e0a4c42f-ce5b-4d49-8a38-ec3a40808b6e.mov

**Comment by rcampany** [comment]
I think my description wasn't clear. Try this screen recording

https://user-images.githubusercontent.com/10439748/167658337-81232041-d07f-4d36-9c20-dbf47d494fbb.mp4

**Comment by brotherclone** [comment]
ohhhhh.... you're getting redirected without the thank you and no info - ha, well yeah that sucks. I will fix, thank you!
