### ISSUE TITLE
Navigation question

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#47]
I *thought* that the red term below the line indicated that I was browsing a category or tag. In this example, the tag is Prince Street, but unrelated memories appear.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/10439748/157516993-eba19a7a-1f92-40bb-878c-c4e2450a7a28.png">

**Comment by brotherclone** [comment]
Notes- 

- Nav category and tag select not behaving correctly on live env. Turbo frame is not resetting and the click action via stimulus does not post correctly to reload the timeline.

**Comment by brotherclone** [comment]
Nav will be redone for Category-Sub-Category version
