### ISSUE TITLE
photo display

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#48]
Questions

- Will there eventually be a function to open a memory? Or will it always be a "slide show" approach?
- If photos will only be a slide show, is there a guideline for cropping, sizing, weighting photos?
Here is an example from Memory 46, where the subject (topic), _Jack, the dog_,  is on the edge of the image
Here is the [original image ](https://drive.google.com/file/d/1fGbG4CHSZ_dMpqg-emt92L9PrVxTGt2a/view?usp=sharing)

<img width="602" alt="image" src="https://user-images.githubusercontent.com/10439748/157519219-84c0b431-d376-4dbf-8ef2-e98ac5add927.png">

**Comment by brotherclone** [comment]
How about a click on the image to open it up in a full screen overlay? This could handle all different sorts of dimensions.

**Comment by rcampany** [comment]
Question: If I were to open the image in the example above, would the related links navigation work? i.e., could I move from one full screen to another?

**Comment by brotherclone** [comment]
Solution is - to pre-crop as a square to ensure it's viewed as intended.
