### ISSUE TITLE
Update title of Guest Book

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#49]
Peter would like to call it, 
_Leave your outrageous memories and photos of Peter_

That's kind of long - any issues with it?

**Comment by brotherclone** [comment]
Could we make it a hover? Like a speech bubble type thing ? It is too long to replace "guest book" but could also be on the guest book page.

**Comment by rcampany** [comment]
how about 
Drop your memories
Add your memories

I think "guest book" sounds like a funeral or a wedding

**Comment by brotherclone** [comment]
Yes, no problem. I can still make the hover state the "Leave your outrageous memories and photos of Peter" if you want.
