### ISSUE TITLE
first image in a load

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#50]
The first image in a load "disappears" as you scroll down.
Here are two examples
One is the default chron load. The other I s load of the category, "upbringing."
The first image disappears before fully in view. Images that follow behave as expected.

https://drive.google.com/file/d/108dWhb0s4ygwhXPQ-BkI9tsO8fpIcexr/view?usp=sharing
https://drive.google.com/file/d/13GVjNDJXKPMuU-X3Ogwyiid_ZyiLYgzU/view?usp=sharing

**Comment by brotherclone** [comment]
botched opacity on the scroll. Will fix. Thanks for the ticket!
