### ISSUE TITLE
The Change you wanted was rejected

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#56]
I was browsing the front end, and this very elegant error message showed up

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/10439748/157928274-a18c5e7f-219a-4993-8303-5b8f49ba01e8.png">

**Comment by brotherclone** [comment]
Be the rejected change you wanna be, man.

**Comment by brotherclone** [comment]
This may be a duplicate of or related to #47

**Comment by brotherclone** [comment]
This navigation will not be in the new version.
