### ISSUE TITLE
New Sub/Category Page

### ISSUE THREAD

**Issue by brotherclone** [brotherclone/peter-koper#63]

**Comment by brotherclone** [comment]
![Category with subs](https://user-images.githubusercontent.com/2085319/158625729-e6f45a4d-6b5b-428b-aaec-e428c7d6df68.png)
![Category with subs – 1](https://user-images.githubusercontent.com/2085319/158625733-78e0e61b-2cd7-44f4-8774-023f43b12dc6.png)

**Comment by brotherclone** [comment]
sub-category 1 on second image not intentionally misaligned. 😞

**Comment by rcampany** [comment]
I like the first one - with categories stacked above each other

<img width="342" alt="image" src="https://user-images.githubusercontent.com/10439748/158628675-12370daf-c6b1-4f76-aebe-e9b05591ffbe.png">
