### ISSUE TITLE
New Headers

### ISSUE THREAD

**Issue by brotherclone** [brotherclone/peter-koper#64]

**Comment by brotherclone** [comment]
![Home](https://user-images.githubusercontent.com/2085319/158625787-346859cb-3ac3-4d58-afe8-c1d011e886f7.png)

**Comment by rcampany** [comment]
How would navigation work?
I could click on either _writing_ or _foreign correspondents_?

<img width="162" alt="image" src="https://user-images.githubusercontent.com/10439748/158628912-2099db11-b7dc-4102-a811-c412eee364e3.png">

And to go back _up_ I would click _select a stroll_?   (which I love, BTW)

**Comment by brotherclone** [comment]
Yes, so you could jump just to Sub-Categories (totally optional as they appear on the category page) stroll - on all other pages this would lead you home - but there's also now a breadcrumb on all pages except home.  (Home/Category/SubCategory). The big thing is that there's no (per the simple-simple-simple feedback) memory collections by tag. We could make an alternate to the category page for this if you want - but there wouldn't be an "all tags" menu or page. Did I get that right?

**Comment by rcampany** [comment]
Peter is a very linear thinker when it comes to the internet–lots of back button action. 
I was honestly not sure what Peter was reacting to. 
Some of the examples we looked at with him were memories that had 2 - 3 categories. That was me experimenting, and that is definitely too much.

It was his initial idea to use tags. I _think_ in the end he was reacting to using tags that would have only 1 (or very few) entry?  He did seem to favor tags for his father, Desperate Living...

**Comment by rcampany** [comment]
So you are on a memory with tags
Stefan, Peter Koper, Baltimore

You click on _Stefan_ and you go to a page with all memories tagged, _Stefan_.

You can click back to the category you came from - OR you could pursue a category or tag link on one of the memories in that batch?
