### ISSUE TITLE
Submission error on editing a memory

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#68]
I tried to edit memory 67. I loaded up a new photo, but it does not save.
This is the new photo file I tried uploading https://drive.google.com/file/d/12p-fWoUAm9385YEKnewTGtLWqOszXRLq/view?usp=sharing 

<img width="948" alt="image" src="https://user-images.githubusercontent.com/10439748/158033277-8ef0bc4b-951f-4d53-83b5-c09671b38ba3.png">

**Comment by rcampany** [comment]
Same happened with memory 29. Must be related to replacing image files

**Comment by brotherclone** [comment]
CLOUDINARY_API_KEY requires casting to string local but needs to be *just* string on prod.
