### ISSUE TITLE
Category icon images

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#93]
I loaded up a 1x1 crop for the category, _Upbringing_.
Do I need to scale to specific dimensions?

<img width="823" alt="image" src="https://user-images.githubusercontent.com/10439748/159139030-26fa0700-9eb9-4583-94d0-a95489e064c3.png">

**Comment by brotherclone** [comment]
no, it's just missing a background-contain for larger sizes. will fix.
