### ISSUE TITLE
photo files not loading

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#94]
Things were working - and now we can't load images.
I'm guessing you are in there working?
memory #90 
<img width="771" alt="image" src="https://user-images.githubusercontent.com/10439748/159170852-9e4184fe-565c-4cb0-8177-8ad08f9cfd0c.png">

**Comment by brotherclone** [comment]
Just fixed. Photos need to be JPEGs. Some of the PNGs are 8-bit  which won't display- so if you can just convert them to JPG before uploading.  If you need me to batch image conversion just let me know

**Comment by rcampany** [comment]
Got it. I somehow thought PNG as preferred. But I can do JPEG

Thank you!
